### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [haseab/ABC#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by haseab** [comment]
Sure go ahead!

**Comment by suprafun** [comment]
Thank you so very much. Would it be possible for you to add a formal license to the project ? I ask because I just want to be sure about how I should treat it as a learning resource. In my case I would like to learn about how you did the time scheduling aspects to come up with this neat planner. Thank you again.

**Comment by haseab** [comment]
Done
